### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by qrmt** [mjhea0/flask-boilerplate#24]
Hello,
it would be nice to use this as a template but it seems that the project does not include a license, making this impossible. If you wish to distribute this freely, could you please include something like a MIT or Apache license?

**Comment by mjhea0** [comment]
Want to issue a PR?

**Comment by alaxalves** [comment]
Pull Request #25 solving issue #24

**Comment by qrmt** [comment]
Very nice! Thanks, alaxalves.
